# Copy to:
# C:\Apache24\conf\extra\src-enterprise.local.conf
#
# Then include it from C:\Apache24\conf\httpd.conf:
# Include conf/extra/src-enterprise.local.conf
# for sharing the app on other devices in same netwrork, ServerAlias OFFICE-SERVER ,via result of hostname
#Restart-Service Apache24
# then use app.baseURL = 'http://OFFICE-SERVER/'


<VirtualHost *:80>
    ServerName src-enterprise.local
    DocumentRoot "C:/src-enterprise/accounts_recievable/ci4-app/public"

    <Directory "C:/src-enterprise/accounts_recievable/ci4-app/public">
        Options FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog "logs/src-enterprise-error.log"
    CustomLog "logs/src-enterprise-access.log" common
</VirtualHost>
